Origin
kerelape/gophkeeper pull request #1
Opened 2023-09-12 11:40 UTC by kerelape

2023-09-12 19:13 UTC, tmvrus requested changes
формальные требования не выполнены
<img width="749" alt="image" src="https://github.com/kerelape/gophkeeper/assets/554425/17bf1c52-526b-49a4-860e-7887ee248f8c">

2023-09-19 16:52 UTC, tmvrus requested changes
- злоупотребление var
 - Fatal внутри слоя хранения
 - игнорирование возможных ошибок transaction.Rollback/Content.Close/
 - не все формальные требования, указанные на предыдущем ревью, выполнены
 - большое количество замечаний

Я честно сделал все что описано в инструкции, но это привело к ошибке
```
./gophkeeper -s "https://localhost:16355" list

failed to execute command list: Post "https://localhost:16355/login": dial tcp [::1]:16355: connect: connection refused

```
видимо нужно поднять серверную часть, но об этом ничего в инструкции не написано

2023-09-19 16:52 UTC, tmvrus commented on internal/cli/authentication.go
> +	if m.(authenticationModel).cancelled {
не стоит использовать type assert без проверки, особенно там где можно вернуть ошибку

2023-09-19 16:52 UTC, tmvrus commented on internal/cli/authentication.go
> +		Password: m.(authenticationModel).password.Value(),
в это ф-и type assert можно было выполнить один раз

2023-09-19 16:52 UTC, tmvrus commented on internal/cli/vault_password.go
> +	return m.(vaultPasswordModel).password.Value(), nil
type assert без проверки плохая практика

2023-09-19 16:52 UTC, tmvrus commented on internal/server/encrypted/identity.go
> +	var iv []byte = make([]byte, block.BlockSize())
нотацию var рекомендуют использовать что бы объявить слайс размер которого заранее не известен,
```
var iv []byte
```
в данном случае размер есть и вполне можно переписать
```
iv := make([]byte, block.BlockSize())
```
это как минимум короче

2023-09-19 16:52 UTC, tmvrus commented on internal/server/encrypted/identity.go
> +		meta{
читать код становится существенно сложнее если давать переменным и типам одинаковые имена

2023-09-19 16:52 UTC, tmvrus commented on internal/server/encrypted/identity.go
> +		return -1, contentError
что это за загадочная -1 известно только автору кода

2023-09-19 16:52 UTC, tmvrus commented on internal/server/encrypted/identity.go
> +	piece.Meta = (string)(meta)
впервые вижу такое приведение к строке, обычно
string(meta)

2023-09-19 16:52 UTC, tmvrus commented on pkg/gophkeeper/rest/identity.go
> +			"content": base64.RawStdEncoding.EncodeToString(([]byte)(piece.Content)),
piece.Content и так типа []byte его не нужно дополнительно конвертировать

2023-09-19 16:52 UTC, tmvrus commented on internal/server/rest/entry.go
> +package rest
у этого пакета все еще отсутствует комментарий

2023-09-19 16:52 UTC, tmvrus commented on internal/server/rest/vault/entry.go
> +package vault
у этого пакета все еще отсутствует комментарий

2023-09-19 16:52 UTC, tmvrus commented on internal/deferred/deferred.go
> +package deferred
у этого пакета отсутствует комментарий

2023-09-19 16:52 UTC, tmvrus commented on internal/server/rest/register/entry.go
> +package register
у пакета отсутствует комментарий

2023-09-19 16:52 UTC, tmvrus commented on internal/server/rest/register/entry.go
> +		http.Error(out, http.StatusText(status), status)
какой смысл отдельно выделять status если сразу написать
http.Error(out, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)

всего остального кода это тоже касается

2023-09-19 16:52 UTC, tmvrus commented on internal/server/postgres/identity.go
> +			return nil, err
log.Fatal вызывает немедленное завершение программы, советую пересмотреть подход к логиованию

2023-09-19 16:52 UTC, tmvrus commented on internal/composed_read_closer/composed_read_closer.go
> +package composedreadcloser
у это пакета тоже нет комментария

2023-09-19 16:52 UTC, tmvrus commented on internal/server/postgres/identity.go
> +	if err := i.comparePassword(ctx, password); err != nil {
слой хранения занимается авторизацией операции, рекомендую пересмотреть такой подход и не смешивать ответственность разных слоев

2023-09-19 16:52 UTC, tmvrus commented on internal/server/postgres/identity.go
> +	defer transaction.Rollback(context.Background())
- ошибку все же лучше проверять
- контекст хорошо бы передавать "настоящий"

2023-09-19 16:52 UTC, tmvrus commented on internal/server/rest/register/entry.go
> +	var requestBody map[string]any
заччем использовать any если далее работа со строкой? можно же спокойно использовать map[string]string

2023-09-19 16:52 UTC, tmvrus commented on internal/server/rest/login/entry.go
> +	var requestBody map[string]any
тут тоже можно использовать map[string]string

2023-09-19 16:52 UTC, tmvrus commented on internal/server/rest/vault/blob/entry.go
> +	}
вот этот код встречается в проекте 6 раз, но middleware обсуждались в течении курса

2023-09-19 16:52 UTC, tmvrus commented on internal/server/rest/vault/blob/entry.go
> +	}
эта часть тоже просится в отдельную ф-ю, потому что встречается в проекте 4 раза

2023-09-19 16:52 UTC, tmvrus commented on cmd/server/main.go
> +		os.Exit(1)
тут можно/нужно использовать log.Fatal

2023-09-22 15:50 UTC, kerelape commented on internal/server/encrypted/identity.go
> +	piece.Meta = (string)(meta)
Я использую эту конвенцию во всем коде, чтобы разлечать вызов функции и приведение типов

2023-09-22 15:51 UTC, kerelape commented on internal/server/encrypted/identity.go
> +		return -1, contentError
Поскольку возвращается ошибка, то `-1` это просто "какое-то" значение. Оно не имеет бизнес-значения и не должно быть использовано никак, из-за ошибки

2023-09-22 15:56 UTC, kerelape commented on internal/server/rest/entry.go
> +package rest
Он `internal`

2023-09-22 15:56 UTC, kerelape commented on internal/server/rest/vault/entry.go
> +package vault
Он `internal`

2023-09-22 15:56 UTC, kerelape commented on internal/deferred/deferred.go
> +package deferred
Он `internal`

2023-09-22 15:56 UTC, kerelape commented on internal/server/rest/register/entry.go
> +package register
Он `internal`

2023-09-22 15:58 UTC, kerelape commented on internal/server/rest/register/entry.go
> +		http.Error(out, http.StatusText(status), status)
Чтобы нельзя было забыть менять в одном месте и не поменять в другом. Не думаю что эта переменная, как то сильно порит читаемость или производительность

2023-09-22 16:03 UTC, kerelape commented on internal/server/postgres/identity.go
> +	if err := i.comparePassword(ctx, password); err != nil {
Это не столько авторизация, сколько валидация - эта проверка нужна чтобы помочь пользователю не зашифровать данные неправильным паролем, так как он используется при шифровании. Согласен, что с архетектурной точки зрения в этом есть проблема, но она требует более глобального рефакторинга

2023-09-26 11:10 UTC, tmvrus commented on internal/server/encrypted/identity.go
> +		return -1, contentError
рекомендую все же глубже ознакомиться с термином "магическая константа"

2023-09-26 11:13 UTC, tmvrus commented on internal/server/encrypted/identity.go
> +	piece.Meta = (string)(meta)
Звучит все еще странно, нельзя без существенных правок кода создать ф-ю string что бы различать ее вызов и приведение к типу string

2023-09-26 11:14 UTC, tmvrus commented on internal/server/rest/entry.go
> +package rest
<img width="729" alt="image" src="https://github.com/kerelape/gophkeeper/assets/554425/f7ff04a5-5be3-4b12-953d-73ba30e4557e">
тут ничего не сказано про internal

2023-09-26 11:15 UTC, tmvrus commented on internal/server/rest/register/entry.go
> +		http.Error(out, http.StatusText(status), status)
что бы нельзя было забыть, не нужно заниматься дублированием кода

2023-09-26 11:18 UTC, tmvrus requested changes
проверить так и не удалось:
клиент
```
>./gophkeeper -s "https://localhost:16355" register
Type new identity's username: test
Type new identity's password: 
Retype new identity's password: 
failed to execute command register: Post "https://localhost:16355/register": remote error: tls: internal error
```

сервер

```
DATABASE_DSN="postgres://test:@127.0.0.1:5432/kerelape" TOKEN_SECRET="af" ./gophserver 
[RUNNABLE] 2023/09/26 14:17:49 manager: postgres.Gophkeeper started
[RUNNABLE] 2023/09/26 14:17:49 manager: rest.Rest started
[GOPHKEEPER] 2023/09/26 14:17:58 http: TLS handshake error from [::1]:56201: acme/autocert: server name component count invalid
```

2023-09-26 11:32 UTC, kerelape commented on internal/server/rest/entry.go
> +package rest
["We propose a mechanism for defining packages that can only be imported by nearby code, not by any other package." - Go 1.4 “Internal” Packages](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU)

Как мне кажется, это означает, что internal пакеты - это, как раз неэкспортируемые пакеты системы

2023-09-26 11:48 UTC, tmvrus commented on internal/server/rest/entry.go
> +package rest
пакет не может быть "неэкспортируемым" иначе в нем нет никакого смысла, internal управляет только тем кто может этот пакет подключить а кто нет

2023-09-28 10:28 UTC, tmvrus requested changes
```
./gophkeeper -s "http://localhost:16355" store-file ./go.mod
failed to execute command store-file: server is down
```
видео воспроизведения
https://disk.yandex.ru/i/PQw1Y1rDycUypg

2023-11-01 15:35 UTC, arttet commented
Please update the PR description and add info about code coverage: https://app.codecov.io/gh/kerelape/gophkeeper/tree/origin

2023-11-24 09:49 UTC, merged